<h1>show list of Categories<h1>
    
<?php
/*$productId = 2; // YOUR PRODUCT ID
$product = $block->getProductById($productId);

// for current product
// $product = $block->getCurrentProduct();

$categoryIds = $product->getCategoryIds();

$categories = $block->getCategoryCollection()
                    ->addAttributeToFilter('entity_id', $categoryIds);
					
foreach ($categories as $category) {
    echo $category->getName() . '<br>';
}
*/


$parentCategoryId = 8;

$productCollection = $block->getProductCollection($parentCategoryId);






?>
<div class="inspire-me"> 
    <ul class="row list">
        <?php foreach ($productCollection as $product): ?>

          <?php //echo print_r($product->getData()); ?>
      
           <li>
                <span><?php echo $product->getUrl(); ?></span>
                <span><?php echo $product->getSku(). ' - '. $product->getName() ?></span>
                <span><?php echo $product->getPrice(); ?></span>
            </li>
        <?php endforeach; ?>    
    </ul>
</div>
